### PR TITLE
Reset

### PR DESCRIPTION
**Pull request by programmingmind**

### CODE REVIEW

**Comment by devongovett** [comment]
WTF did you do?

**Comment by programmingmind** [comment]
I had to rebase from master which included all the shit we got rid of and all of the recent changes. I had to do this because his branch doesn't have the alarm predictor stuff I needed

**Comment by devongovett** [comment]
so nasty. any way around it?

**Comment by programmingmind** [comment]
not really. this is the way to get his branch up to master so that I can use the new features in it

**Comment by devongovett** [comment]
Usually the diffs don't include commits that are already in master though. I'll merge it, but this still seems weird and I have no clue what you actually changed.

**Comment by devongovett** [comment]
Like, why are my commits in there? those commits are already in master.

**Comment by programmingmind** [comment]
only the last 2 commits are what I changed

**Comment by programmingmind** [comment]
I'm not merging into master, I'm merging into preferences

**Comment by devongovett** [comment]
ohhhh. I get it. so confusing.

**Pull request merged**
